export const data = [
    {
      title: 'Javascript',
      items: [
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'medium',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'hard',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
      ],
    },
    {
      title: 'React',
      items: [
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'medium',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'hard',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
      ],
    },
    {
      title: 'Assignments',
      items: [
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'medium',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'hard',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
        {
          heading: 'Develop a auto complete typeahead',
          difficulty: 'easy',
          codeLink: 'https://saurabhsen.me',
          liveLink: 'https://saurabhsen.me',
          authorName: 'Saurabh Sen',
          authorLink: 'https://saurabhsen.me',
        },
      ],
    }
  ]